language: cpp
cache: ccache
services:
  - docker
os:
  - linux
env:
  - JOB=PRE_COMMIT

matrix:
  include:
    - python: 2.7
      addons:
        apt:
          packages:
            - git
            - python
            - python-pip
            - python2.7-dev
        ssh_known_hosts: 13.229.163.131
    - python: 3.7
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - git
            - python3.7-dev
         ssh_known_hosts: 13.229.163.131

before_install:
  - sudo pip install -U virtualenv pre-commit pip

script:
  - exit_code=0
  - .travis/precommit.sh || exit_code=$(( exit_code | $? ))

notifications:
  email:
    on_success: change
    on_failure: always
