language: cpp
cache: ccache
services:
  - docker
os:
  - linux
env:
  - JOB=PRE_COMMIT

matrix:
  include:
    - python: 2.7
      addons:
        apt:
          packages:
            - git
            - python
            - python-pip
            - python2.7-dev
        ssh_known_hosts: 13.229.163.131
    - python: 3.6
      addons:
        apt:
          packages:
            - git
            - python3.6
            - python3.6-pip
            - python3.6-dev
        ssh_known_hosts: 13.229.163.131

before_install:
  - sudo pip install -U virtualenv pre-commit pip

script:
  - exit_code=0
  - .travis/precommit.sh || exit_code=$(( exit_code | $? ))

notifications:
  email:
    on_success: change
    on_failure: always
